# Terraform configuration for meitar_instance module
# Generated by Module Builder Agent

terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "6.27.0"
    }
  }
}

# Provider configuration
# Note: Provider should be configured by the caller, not in the module
# This is a best practice for reusable modules
